//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HangmanData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Game
    {
        public int id { get; set; }
        public int player_id { get; set; }
        public string difficulty { get; set; }
        public int mistakes { get; set; }
        public bool won { get; set; }
        public System.DateTime date { get; set; }
        public int duration { get; set; }
    }
}
